### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by 5colors** [chanxuehong/session#1]
I want to use [Sourcegraph](https://sourcegraph.com) for session code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/chanxuehong/session. (It should only take 30 seconds.)

Thank you!

**Comment by chanxuehong** [comment]
It is building, lasted a long time, please wait. You're welcome
